<?php
    // Define Global Array of Social Networks
    $this->TS_VCSC_Social_Networks_Array = array(
        "Email"                         => array("order" => 0, "class" => "email"),
        "Phone"                         => array("order" => 1, "class" => "phone"),
        "Cell"                          => array("order" => 2, "class" => "cell"),
        "Portfolio"                     => array("order" => 3, "class" => "portfolio"),
        "Link"                          => array("order" => 4, "class" => "link"),
        "Behance"                       => array("order" => 5, "class" => "behance"),
        "Digg"                          => array("order" => 6, "class" => "digg"),
        "Dribbble"                      => array("order" => 7, "class" => "dribbble"),
        "Dropbox"                       => array("order" => 8, "class" => "dropbox"),
        "Envato"                        => array("order" => 9, "class" => "envato"),
        "EverNote"                      => array("order" => 10, "class" => "evernote"),
        "Facebook"                      => array("order" => 11, "class" => "facebook"),
        "Flickr"                        => array("order" => 12, "class" => "flickr"),
        "Github"                        => array("order" => 13, "class" => "github"),
        "Google+"                       => array("order" => 14, "class" => "gplus"),
        "Instagram"                     => array("order" => 15, "class" => "instagram"),
        "LastFM"                        => array("order" => 16, "class" => "lastfm"),
        "LinkedIn"                      => array("order" => 17, "class" => "linkedin"),
        "Paypal"                        => array("order" => 18, "class" => "paypal"),
        "Picasa"                        => array("order" => 19, "class" => "picasa"),
        "Pinterest"                     => array("order" => 20, "class" => "pinterest"),
        "RSS"                           => array("order" => 21, "class" => "rss"),
        "Skype"                         => array("order" => 22, "class" => "skype"),
        "Soundcloud"                    => array("order" => 23, "class" => "soundcloud"),
        "Spotify"                       => array("order" => 24, "class" => "spotify"),
        "StumbleUpon"                   => array("order" => 25, "class" => "stumbleupon"),
        "Twitter"                       => array("order" => 26, "class" => "twitter"),
        "Tumblr"                        => array("order" => 27, "class" => "tumblr"),
        "Vimeo"                         => array("order" => 28, "class" => "vimeo"),
        "Xing"                          => array("order" => 29, "class" => "xing"),
        "YouTube"                       => array("order" => 30, "class" => "youtube"),
    );
    
    // Timezones Options
    $this->TS_VCSC_Timezones = array(
        'Local / Server Time'           => "false",
        'Pacific/Midway'                => "(GMT-11:00) Midway Island",
        'US/Samoa'                      => "(GMT-11:00) Samoa",
        'US/Hawaii'                     => "(GMT-10:00) Hawaii",
        'US/Alaska'                     => "(GMT-09:00) Alaska",
        'US/Pacific'                    => "(GMT-08:00) Pacific Time (US &amp; Canada)",
        'America/Tijuana'               => "(GMT-08:00) Tijuana",
        'US/Arizona'                    => "(GMT-07:00) Arizona",
        'US/Mountain'                   => "(GMT-07:00) Mountain Time (US &amp; Canada)",
        'America/Chihuahua'             => "(GMT-07:00) Chihuahua",
        'America/Mazatlan'              => "(GMT-07:00) Mazatlan",
        'America/Mexico_City'           => "(GMT-06:00) Mexico City",
        'America/Monterrey'             => "(GMT-06:00) Monterrey",
        'Canada/Saskatchewan'           => "(GMT-06:00) Saskatchewan",
        'US/Central'                    => "(GMT-06:00) Central Time (US &amp; Canada)",
        'US/Eastern'                    => "(GMT-05:00) Eastern Time (US &amp; Canada)",
        'US/East-Indiana'               => "(GMT-05:00) Indiana (East)",
        'America/Bogota'                => "(GMT-05:00) Bogota",
        'America/Lima'                  => "(GMT-05:00) Lima",
        'America/Caracas'               => "(GMT-04:30) Caracas",
        'Canada/Atlantic'               => "(GMT-04:00) Atlantic Time (Canada)",
        'America/La_Paz'                => "(GMT-04:00) La Paz",
        'America/Santiago'              => "(GMT-04:00) Santiago",
        'Canada/Newfoundland'           => "(GMT-03:30) Newfoundland",
        'America/Buenos_Aires'          => "(GMT-03:00) Buenos Aires",
        'Greenland'                     => "(GMT-03:00) Greenland",
        'Atlantic/Stanley'              => "(GMT-02:00) Stanley",
        'Atlantic/Azores'               => "(GMT-01:00) Azores",
        'Atlantic/Cape_Verde'           => "(GMT-01:00) Cape Verde Is.",
        'Africa/Casablanca'             => "(GMT) Casablanca",
        'Europe/Dublin'                 => "(GMT) Dublin",
        'Europe/Lisbon'                 => "(GMT) Lisbon",
        'Europe/London'                 => "(GMT) London",
        'Africa/Monrovia'               => "(GMT) Monrovia",
        'Europe/Amsterdam'              => "(GMT+01:00) Amsterdam",
        'Europe/Belgrade'               => "(GMT+01:00) Belgrade",
        'Europe/Berlin'                 => "(GMT+01:00) Berlin",
        'Europe/Bratislava'             => "(GMT+01:00) Bratislava",
        'Europe/Brussels'               => "(GMT+01:00) Brussels",
        'Europe/Budapest'               => "(GMT+01:00) Budapest",
        'Europe/Copenhagen'             => "(GMT+01:00) Copenhagen",
        'Europe/Ljubljana'              => "(GMT+01:00) Ljubljana",
        'Europe/Madrid'                 => "(GMT+01:00) Madrid",
        'Europe/Paris'                  => "(GMT+01:00) Paris",
        'Europe/Prague'                 => "(GMT+01:00) Prague",
        'Europe/Rome'                   => "(GMT+01:00) Rome",
        'Europe/Sarajevo'               => "(GMT+01:00) Sarajevo",
        'Europe/Skopje'                 => "(GMT+01:00) Skopje",
        'Europe/Stockholm'              => "(GMT+01:00) Stockholm",
        'Europe/Vienna'                 => "(GMT+01:00) Vienna",
        'Europe/Warsaw'                 => "(GMT+01:00) Warsaw",
        'Europe/Zagreb'                 => "(GMT+01:00) Zagreb",
        'Europe/Athens'                 => "(GMT+02:00) Athens",
        'Europe/Bucharest'              => "(GMT+02:00) Bucharest",
        'Africa/Cairo'                  => "(GMT+02:00) Cairo",
        'Africa/Harare'                 => "(GMT+02:00) Harare",
        'Europe/Helsinki'               => "(GMT+02:00) Helsinki",
        'Europe/Istanbul'               => "(GMT+02:00) Istanbul",
        'Asia/Jerusalem'                => "(GMT+02:00) Jerusalem",
        'Europe/Kiev'                   => "(GMT+02:00) Kyiv",
        'Europe/Minsk'                  => "(GMT+02:00) Minsk",
        'Europe/Riga'                   => "(GMT+02:00) Riga",
        'Europe/Sofia'                  => "(GMT+02:00) Sofia",
        'Europe/Tallinn'                => "(GMT+02:00) Tallinn",
        'Europe/Vilnius'                => "(GMT+02:00) Vilnius",
        'Asia/Baghdad'                  => "(GMT+03:00) Baghdad",
        'Asia/Kuwait'                   => "(GMT+03:00) Kuwait",
        'Africa/Nairobi'                => "(GMT+03:00) Nairobi",
        'Asia/Riyadh'                   => "(GMT+03:00) Riyadh",
        'Asia/Tehran'                   => "(GMT+03:30) Tehran",
        'Europe/Moscow'                 => "(GMT+04:00) Moscow",
        'Asia/Baku'                     => "(GMT+04:00) Baku",
        'Europe/Volgograd'              => "(GMT+04:00) Volgograd",
        'Asia/Muscat'                   => "(GMT+04:00) Muscat",
        'Asia/Tbilisi'                  => "(GMT+04:00) Tbilisi",
        'Asia/Yerevan'                  => "(GMT+04:00) Yerevan",
        'Asia/Kabul'                    => "(GMT+04:30) Kabul",
        'Asia/Karachi'                  => "(GMT+05:00) Karachi",
        'Asia/Tashkent'                 => "(GMT+05:00) Tashkent",
        'Asia/Kolkata'                  => "(GMT+05:30) Kolkata",
        'Asia/Kathmandu'                => "(GMT+05:45) Kathmandu",
        'Asia/Yekaterinburg'            => "(GMT+06:00) Ekaterinburg",
        'Asia/Almaty'                   => "(GMT+06:00) Almaty",
        'Asia/Dhaka'                    => "(GMT+06:00) Dhaka",
        'Asia/Novosibirsk'              => "(GMT+07:00) Novosibirsk",
        'Asia/Bangkok'                  => "(GMT+07:00) Bangkok",
        'Asia/Jakarta'                  => "(GMT+07:00) Jakarta",
        'Asia/Krasnoyarsk'              => "(GMT+08:00) Krasnoyarsk",
        'Asia/Chongqing'                => "(GMT+08:00) Chongqing",
        'Asia/Hong_Kong'                => "(GMT+08:00) Hong Kong",
        'Asia/Kuala_Lumpur'             => "(GMT+08:00) Kuala Lumpur",
        'Australia/Perth'               => "(GMT+08:00) Perth",
        'Asia/Singapore'                => "(GMT+08:00) Singapore",
        'Asia/Taipei'                   => "(GMT+08:00) Taipei",
        'Asia/Ulaanbaatar'              => "(GMT+08:00) Ulaan Bataar",
        'Asia/Urumqi'                   => "(GMT+08:00) Urumqi",
        'Asia/Irkutsk'                  => "(GMT+09:00) Irkutsk",
        'Asia/Seoul'                    => "(GMT+09:00) Seoul",
        'Asia/Tokyo'                    => "(GMT+09:00) Tokyo",
        'Australia/Adelaide'            => "(GMT+09:30) Adelaide",
        'Australia/Darwin'              => "(GMT+09:30) Darwin",
        'Asia/Yakutsk'                  => "(GMT+10:00) Yakutsk",
        'Australia/Brisbane'            => "(GMT+10:00) Brisbane",
        'Australia/Canberra'            => "(GMT+10:00) Canberra",
        'Pacific/Guam'                  => "(GMT+10:00) Guam",
        'Australia/Hobart'              => "(GMT+10:00) Hobart",
        'Australia/Melbourne'           => "(GMT+10:00) Melbourne",
        'Pacific/Port_Moresby'          => "(GMT+10:00) Port Moresby",
        'Australia/Sydney'              => "(GMT+10:00) Sydney",
        'Asia/Vladivostok'              => "(GMT+11:00) Vladivostok",
        'Asia/Magadan'                  => "(GMT+12:00) Magadan",
        'Pacific/Auckland'              => "(GMT+12:00) Auckland",
        'Pacific/Fiji'                  => "(GMT+12:00) Fiji",
    );
    
    // Google GeoMap Chart Options
    $this->TS_VCSC_GeoMap_Regions = array(
        "World"                                                 => "world",
        "Continent: Africa"                                     => "002",
        "Continent: Europe"                                     => "150",
        "Continent: Americas"                                   => "019",
        "Continent: Asia"                                       => "142",
        "Continent: Oceania"                                    => "009",
        "Sub-Continent: Africa - Northern"                      => "015",
        "Sub-Continent: Africa - Western"                       => "011",
        "Sub-Continent: Africa - Middle"                        => "017",
        "Sub-Continent: Africa - Eastern"                       => "014",
        "Sub-Continent: Africa - Southern"                      => "018",
        "Sub-Continent: Europe - Northern"                      => "154",
        "Sub-Continent: Europe - Western"                       => "155",
        "Sub-Continent: Europe - Eastern"                       => "151",
        "Sub-Continent: Europe - Southern"                      => "039",
        "Sub-Continent: Americas - Northern"                    => "021",
        "Sub-Continent: Americas - Caribbean"                   => "029",
        "Sub-Continent: Americas - Central"                     => "013",
        "Sub-Continent: Americas - South"                       => "005",
        "Sub-Continent: Asia - Central"                         => "143",
        "Sub-Continent: Asia - Eastern"                         => "030",
        "Sub-Continent: Asia - Southern"                        => "034",
        "Sub-Continent: Asia - Southern-Eastern"                => "035",
        "Sub-Continent: Asia - Western"                         => "145",
        "Sub-Continent: Oceania - Australia and New Zealand"    => "053",
        "Sub-Continent: Oceania - Melanesia"                    => "054",
        "Sub-Continent: Oceania - Micronesia"                   => "057",
        "Sub-Continent: Oceania - Polynesia"                    => "061",
        "Country: Afghanistan"                                  => "AF",
        "Country: Aland Islands"                                => "AX",
        "Country: Albania"                                      => "AL",
        "Country: Algeria"                                      => "DZ",
        "Country: American Samoa"                               => "AS",
        "Country: Andorra"                                      => "AD",
        "Country: Angola"                                       => "AO",
        "Country: Anguilla"                                     => "AI",
        "Country: Antarctica"                                   => "AQ",
        "Country: Antigua and Barbuda"                          => "AG",
        "Country: Argentina"                                    => "AR",
        "Country: Armenia"                                      => "AM",
        "Country: Aruba"                                        => "AW",
        "Country: Australia"                                    => "AU",
        "Country: Austria"                                      => "AT",
        "Country: Azerbaijan"                                   => "AZ",
        "Country: Bahamas"                                      => "BS",
        "Country: Bahrain"                                      => "BH",
        "Country: Bangladesh"                                   => "BD",
        "Country: Barbados"                                     => "BB",
        "Country: Belarus"                                      => "BY",
        "Country: Belgium"                                      => "BE",
        "Country: Belize"                                       => "BZ",
        "Country: Benin"                                        => "BJ",
        "Country: Bermuda"                                      => "BM",
        "Country: Bhutan"                                       => "BT",
        "Country: Bolivia, Plurinational State of"              => "BO",
        "Country: Bonaire, Sint Eustatius and Saba"             => "BQ",
        "Country: Bosnia and Herzegovina"                       => "BA",
        "Country: Botswana"                                     => "BW",
        "Country: Bouvet Island"                                => "BV",
        "Country: Brazil"                                       => "BR",
        "Country: British Indian Ocean Territory"               => "IO",
        "Country: Brunei Darussalam"                            => "BN",
        "Country: Bulgaria"                                     => "BG",
        "Country: Burkina Faso"                                 => "BF",
        "Country: Burundi"                                      => "BI",
        "Country: Cambodia"                                     => "KH",
        "Country: Cameroon"                                     => "CM",
        "Country: Canada"                                       => "CA",
        "Country: Cape Verde"                                   => "CV",
        "Country: Cayman Islands"                               => "KY",
        "Country: Central African Republic"                     => "CF",
        "Country: Chad"                                         => "TD",
        "Country: Chile"                                        => "CL",
        "Country: China"                                        => "CN",
        "Country: Christmas Island"                             => "CX",
        "Country: Cocos (Keeling) Islands"                      => "CC",
        "Country: Colombia"                                     => "CO",
        "Country: Comoros"                                      => "KM",
        "Country: Congo"                                        => "CG",
        "Country: Congo, the Democratic Republic of the"        => "CD",
        "Country: Cook Islands"                                 => "CK",
        "Country: Costa Rica"                                   => "CR",
        "Country: Cote d'Ivoire"                                => "CI",
        "Country: Croatia"                                      => "HR",
        "Country: Cuba"                                         => "CU",
        "Country: Curacao"                                      => "CW",
        "Country: Cyprus"                                       => "CY",
        "Country: Czech Republic"                               => "CZ",
        "Country: Denmark"                                      => "DK",
        "Country: Djibouti"                                     => "DJ",
        "Country: Dominica"                                     => "DM",
        "Country: Dominican Republic"                           => "DO",
        "Country: Ecuador"                                      => "EC",
        "Country: Egypt"                                        => "EG",
        "Country: El Salvador"                                  => "SV",
        "Country: Equatorial Guinea"                            => "GQ",
        "Country: Eritrea"                                      => "ER",
        "Country: Estonia"                                      => "EE",
        "Country: Ethiopia"                                     => "ET",
        "Country: Falkland Islands (Malvinas)"                  => "FK",
        "Country: Faroe Islands"                                => "FO",
        "Country: Fiji"                                         => "FJ",
        "Country: Finland"                                      => "FI",
        "Country: France"                                       => "FR",
        "Country: French Guiana"                                => "GF",
        "Country: French Polynesia"                             => "PF",
        "Country: French Southern Territories"                  => "TF",
        "Country: Gabon"                                        => "GA",
        "Country: Gambia"                                       => "GM",
        "Country: Georgia"                                      => "GE",
        "Country: Germany"                                      => "DE",
        "Country: Ghana"                                        => "GH",
        "Country: Gibraltar"                                    => "GI",
        "Country: Greece"                                       => "GR",
        "Country: Greenland"                                    => "GL",
        "Country: Grenada"                                      => "GD",
        "Country: Guadeloupe"                                   => "GP",
        "Country: Guam"                                         => "GU",
        "Country: Guatemala"                                    => "GT",
        "Country: Guernsey"                                     => "GG",
        "Country: Guinea"                                       => "GN",
        "Country: Guinea-Bissau"                                => "GW",
        "Country: Guyana"                                       => "GY",
        "Country: Haiti"                                        => "HT",
        "Country: Heard Island and McDonald Islands"            => "HM",
        "Country: Holy See (Vatican City State)"                => "VA",
        "Country: Honduras"                                     => "HN",
        "Country: Hong Kong"                                    => "HK",
        "Country: Hungary"                                      => "HU",
        "Country: Iceland"                                      => "IS",
        "Country: India"                                        => "IN",
        "Country: Indonesia"                                    => "ID",
        "Country: Iran, Islamic Republic of"                    => "IR",
        "Country: Iraq"                                         => "IQ",
        "Country: Ireland"                                      => "IE",
        "Country: Isle of Man"                                  => "IM",
        "Country: Israel"                                       => "IL",
        "Country: Italy"                                        => "IT",
        "Country: Jamaica"                                      => "JM",
        "Country: Japan"                                        => "JP",
        "Country: Jersey"                                       => "JE",
        "Country: Jordan"                                       => "JO",
        "Country: Kazakhstan"                                   => "KZ",
        "Country: Kenya"                                        => "KE",
        "Country: Kiribati"                                     => "KI",
        "Country: Korea, Democratic People's Republic of"       => "KP",
        "Country: Korea, Republic of"                           => "KR",
        "Country: Kuwait"                                       => "KW",
        "Country: Kyrgyzstan"                                   => "KG",
        "Country: Lao People's Democratic Republic"             => "LA",
        "Country: Latvia"                                       => "LV",
        "Country: Lebanon"                                      => "LB",
        "Country: Lesotho"                                      => "LS",
        "Country: Liberia"                                      => "LR",
        "Country: Libya"                                        => "LY",
        "Country: Liechtenstein"                                => "LI",
        "Country: Lithuania"                                    => "LT",
        "Country: Luxembourg"                                   => "LU",
        "Country: Macao"                                        => "MO",
        "Country: Macedonia, the former Yugoslav Republic of"   => "MK",
        "Country: Madagascar"                                   => "MG",
        "Country: Malawi"                                       => "MW",
        "Country: Malaysia"                                     => "MY",
        "Country: Maldives"                                     => "MV",
        "Country: Mali"                                         => "ML",
        "Country: Malta"                                        => "MT",
        "Country: Marshall Islands"                             => "MH",
        "Country: Martinique"                                   => "MQ",
        "Country: Mauritania"                                   => "MR",
        "Country: Mauritius"                                    => "MU",
        "Country: Mayotte"                                      => "YT",
        "Country: Mexico"                                       => "MX",
        "Country: Micronesia, Federated States of"              => "FM",
        "Country: Moldova, Republic of"                         => "MD",
        "Country: Monaco"                                       => "MC",
        "Country: Mongolia"                                     => "MN",
        "Country: Montenegro"                                   => "ME",
        "Country: Montserrat"                                   => "MS",
        "Country: Morocco"                                      => "MA",
        "Country: Mozambique"                                   => "MZ",
        "Country: Myanmar"                                      => "MM",
        "Country: Namibia"                                      => "NA",
        "Country: Nauru"                                        => "NR",
        "Country: Nepal"                                        => "NP",
        "Country: Netherlands"                                  => "NL",
        "Country: New Caledonia"                                => "NC",
        "Country: New Zealand"                                  => "NZ",
        "Country: Nicaragua"                                    => "NI",
        "Country: Niger"                                        => "NE",
        "Country: Nigeria"                                      => "NG",
        "Country: Niue"                                         => "NU",
        "Country: Norfolk Island"                               => "NF",
        "Country: Northern Mariana Islands"                     => "MP",
        "Country: Norway"                                       => "NO",
        "Country: Oman"                                         => "OM",
        "Country: Pakistan"                                     => "PK",
        "Country: Palau"                                        => "PW",
        "Country: Palestine, State of"                          => "PS",
        "Country: Panama"                                       => "PA",
        "Country: Papua New Guinea"                             => "PG",
        "Country: Paraguay"                                     => "PY",
        "Country: Peru"                                         => "PE",
        "Country: Philippines"                                  => "PH",
        "Country: Pitcairn"                                     => "PN",
        "Country: Poland"                                       => "PL",
        "Country: Portugal"                                     => "PT",
        "Country: Puerto Rico"                                  => "PR",
        "Country: Qatar"                                        => "QA",
        "Country: Reunion"                                      => "RE",
        "Country: Romania"                                      => "RO",
        "Country: Russian Federation"                           => "RU",
        "Country: Rwanda"                                       => "RW",
        "Country: Saint Barthelemy"                             => "BL",
        "Country: Saint Helena, Ascension and Tristan da Cunha" => "SH",
        "Country: Saint Kitts and Nevis"                        => "KN",
        "Country: Saint Lucia"                                  => "LC",
        "Country: Saint Martin (French Part)"                   => "MF",
        "Country: Saint Pierre and Miquelon"                    => "PM",
        "Country: Saint Vincent and the Grenadines"             => "VC",
        "Country: Samoa"                                        => "WS",
        "Country: San Marino"                                   => "SM",
        "Country: Sao Tome and Principe"                        => "ST",
        "Country: Saudi Arabia"                                 => "SA",
        "Country: Senegal"                                      => "SN",
        "Country: Serbia"                                       => "RS",
        "Country: Seychelles"                                   => "SC",
        "Country: Sierra Leone"                                 => "SL",
        "Country: Singapore"                                    => "SG",
        "Country: Sint Maarten (Dutch part)"                    => "SX",
        "Country: Slovakia"                                     => "SK",
        "Country: Slovenia"                                     => "SI",
        "Country: Solomon Islands"                              => "SB",
        "Country: Somalia"                                      => "SO",
        "Country: South Africa"                                 => "ZA",
        "Country: South Georgia and the South Sandwich Islands" => "GS",
        "Country: South Sudan"                                  => "SS",
        "Country: Spain"                                        => "ES",
        "Country: Sri Lanka"                                    => "LK",
        "Country: Sudan"                                        => "SD",
        "Country: Suriname"                                     => "SR",
        "Country: Svalbard and Jan Mayen"                       => "SJ",
        "Country: Swaziland"                                    => "SZ",
        "Country: Sweden"                                       => "SE",
        "Country: Switzerland"                                  => "CH",
        "Country: Syrian Arab Republic"                         => "SY",
        "Country: Taiwan, Province of China"                    => "TW",
        "Country: Tajikistan"                                   => "TJ",
        "Country: Tanzania, United Republic of"                 => "TZ",
        "Country: Thailand"                                     => "TH",
        "Country: Timor-Leste"                                  => "TL",
        "Country: Togo"                                         => "TG",
        "Country: Tokelau"                                      => "TK",
        "Country: Tonga"                                        => "TO",
        "Country: Trinidad and Tobago"                          => "TT",
        "Country: Tunisia"                                      => "TN",
        "Country: Turkey"                                       => "TR",
        "Country: Turkmenistan"                                 => "TM",
        "Country: Turks and Caicos Islands"                     => "TC",
        "Country: Tuvalu"                                       => "TV",
        "Country: Uganda"                                       => "UG",
        "Country: Ukraine"                                      => "UA",
        "Country: United Arab Emirates"                         => "AE",
        "Country: United Kingdom"                               => "GB",
        "Country: United States"                                => "US",
        "Country: United States Minor Outlying Islands"         => "UM",
        "Country: Uruguay"                                      => "UY",
        "Country: Uzbekistan"                                   => "UZ",
        "Country: Vanuatu"                                      => "VU",
        "Country: Venezuela, Bolivarian Republic of"            => "VE",
        "Country: Viet Nam"                                     => "VN",
        "Country: Virgin Islands, British"                      => "VG",
        "Country: Virgin Islands, U.S."                         => "VI",
        "Country: Wallis and Futuna"                            => "WF",
        "Country: Western Sahara"                               => "EH",
        "Country: Yemen"                                        => "YE",
        "Country: Zambia"                                       => "ZM",
        "Country: Zimbabwe"                                     => "ZW",
    );
    
    
    // Social Link Styles
    $this->TS_VCSC_SocialLink_Styles = array(
        "Square"                        => "square",
        "Rounded"                       => "rounded",
        "Circle"                        => "circle",
    );
    
    
    // Divider Text Positions
    $this->TS_VCSC_DividerText_Position = array(
        "Center"                        => "center",
        "Left"                          => "left",
        "Right"                         => "right",
    );
    
    // Tooltip Arrays
    $this->TS_VCSC_Tooltip_Style = array(
        "Black"                         => "",
        "Gray"                          => "ts-simptip-style-gray",
        "Green"                         => "ts-simptip-style-green",
        "Blue"                          => "ts-simptip-style-blue",
        "Red"                           => "ts-simptip-style-red",
        "Orange"                        => "ts-simptip-style-orange",
        "Yellow"                        => "ts-simptip-style-yellow",
        "Purple"                        => "ts-simptip-style-purple",
        "Pink"                          => "ts-simptip-style-pink",
        "White"                         => "ts-simptip-style-white"
    );
    $this->TS_VCSC_OtherTooltip_Position = array(
        "Top"                           => "ts-simptip-position-top",
        "Right"                         => "ts-simptip-position-right",
        "Bottom"                        => "ts-simptip-position-bottom",
        "Left"                          => "ts-simptip-position-left"
    );
    $this->TS_VCSC_ImageTooltip_Position = array(
        "Top"                           => "ts-simptip-position-top",
        "Bottom"                        => "ts-simptip-position-bottom",
    );
    
    // Define Array for Image Switch Types
    $this->TS_VCSC_ImageSwitch_Type = array(
        "Flip"                          => "ts-imageswitch-flip",
        "Slide"                         => "ts-imageswitch-slide",
        "Fade"                          => "ts-imageswitch-fade",
    );
    $this->TS_VCSC_ImageSwitch_Type_Values = array(
        'ts-imageswitch-flip', 'ts-imageswitch-hover'
    );
    
    // Define Array for Trigger Types
    $this->TS_VCSC_Trigger_Type = array(
        "Click"                         => "ts-trigger-click",
        "Hover"                         => "ts-trigger-hover",
    );
    
    // Define Array for Image Position
    $this->TS_VCSC_ImageFloat_Type = array(
        "Center"                        => "ts-imagefloat-center",
        "Float Left"                    => "ts-imagefloat-left",
        "Float Right"                   => "ts-imagefloat-right",
    );
    
    // Define Array for Image Hover Types
    $this->TS_VCSC_HoverImage_Type = array(
        "Style 1"                       => "ts-imagehover-style1",
        "Style 2"                       => "ts-imagehover-style2",
        "Style 3"                       => "ts-imagehover-style3",
        "Style 4"                       => "ts-imagehover-style4",
        "Style 5"                       => "ts-imagehover-style5",
        "Style 6"                       => "ts-imagehover-style6",
        "Style 7"                       => "ts-imagehover-style7",
        "Style 8"                       => "ts-imagehover-style8",
    );
    
    // Define Array for Adipoli Start Effect
    $this->TS_VCSC_AdipoliStart_Type = array(
        "Grayscale (CSS3)"              => "grayscale",
        "Washout"                       => "transparent",
        "Overlay"                       => "overlay",
        //"Normal"                      => "normal",
    );
    
    // Define Array for Adipoli Hover Effect
    $this->TS_VCSC_AdipoliHover_Type = array(
        "Normal"                        => "normal",
        "Popout"                        => "popout",
        "Slice Down"                    => "sliceDown",
        "Slice Down Left"               => "sliceDownLeft",
        "Slice Up"                      => "sliceUp",
        "Slice Up Left"                 => "sliceUpLeft",
        "Slice Up Random"               => "sliceUpRandom",
        "Slice Up Down"                 => "sliceUpDown",
        "Slice Up Down Left"            => "sliceUpDownLeft",
        "Fold"                          => "fold",
        "Fold Left"                     => "foldLeft",
        "Box Random"                    => "boxRandom",
        "Box Rain"                      => "boxRain",
        "Box Rain Reverse"              => "boxRainReverse",
        "Box Rain Grow"                 => "boxRainGrow",
        "Box Rain Grow Reverse"         => "boxRainGrowReverse",
    );
    
    // Define Array for Border Types
    $this->TS_VCSC_DividerBorder_Type = array(
        "Solid Border"                  => "solid",
        "Dotted Border"                 => "dotted",
        "Dashed Border"                 => "dashed",
        "Double Border"                 => "double",
        "Grouve Border"                 => "groove",
        "Ridge Border"                  => "ridge",
        "Inset Border"                  => "inset",
        "Outset Border"                 => "outset"
    );
    $this->TS_VCSC_Border_Type = array(
        "None"                          => "",
        "Solid Border"                  => "solid",
        "Dotted Border"                 => "dotted",
        "Dashed Border"                 => "dashed",
        "Double Border"                 => "double",
        "Grouve Border"                 => "groove",
        "Ridge Border"                  => "ridge",
        "Inset Border"                  => "inset",
        "Outset Border"                 => "outset"
    );
    $this->TS_VCSC_TitleBorder_Type = array(
        "None"                          => "",
        "Solid Border"                  => "solid",
        "Dotted Border"                 => "dotted",
        "Dashed Border"                 => "dashed",
        "Double Border"                 => "double",
        "Grouve Border"                 => "groove",
        "Ridge Border"                  => "ridge",
        "Inset Border"                  => "inset",
        "Outset Border"                 => "outset",
    );
    $this->TS_VCSC_Border_Type_Values = array(
        'solid', 'dotted', 'dashed', 'double', 'groove', 'ridge', 'inset', 'outset'
    );
    
    // Define Array for Icon Border Radius
    $this->TS_VCSC_Icon_Border_Radius = array(
        "None"                          => "",
        "Small Radius"                  => "ts-radius-small",
        "Medium Radius"                 => "ts-radius-medium",
        "Large Radius"                  => "ts-radius-large",
        "Full Circle"                   => "ts-radius-full"
    );
    $this->TS_VCSC_Icon_Border_Radius_Values = array(
        'ts-radius-small', 'ts-radius-medium', 'ts-radius-large', 'ts-radius-full'
    );
    
    // Define Array for Box Border Radius
    $this->TS_VCSC_Box_Border_Radius = array(
        "None"                          => "",
        "Small Radius"                  => "ts-radius-small",
        "Medium Radius"                 => "ts-radius-medium",
        "Large Radius"                  => "ts-radius-large",
    );
    $this->TS_VCSC_Box_Border_Radius_Values = array(
        'ts-radius-small', 'ts-radius-medium', 'ts-radius-large'
    );
    
    // Define Array for Element Alignment
    $this->TS_VCSC_Element_Align = array(
        "No Align"                      => "none",
        "Float Left"                    => "left",
        "Float Right"                   => "right",
        "Center"                        => "center"
    );
    
    // Define Array for Text Alignment
    $this->TS_VCSC_Text_Align = array(
        "Center"                        => "center",
        "Left"                          => "left",
        "Right"                         => "right",
        "Justify"                       => "justify"
    );
    
    // Define Array for Title Alignment
    $this->TS_VCSC_Title_Align = array(
        "Center"                        => "center",
        "Left"                          => "left",
        "Right"                         => "right",
    );
    
    // Define Array for Title Types
    $this->TS_VCSC_Title_Types = array(
        "Standard Div"                  => "div",
        "Standard Span"                 => "span",
        "Standard Paragraph"            => "p",
        "Heading 1"                     => "h1",
        "Heading 2"                     => "h2",
        "Heading 3"                     => "h3",
        "Heading 4"                     => "h4",
        "Heading 5"                     => "h5",
        "Heading 6"                     => "h6",
    );
    
    // Define Array for Link Targets
    $this->TS_VCSC_Link_Target = array(
        "Same Window"                   => "_parent",
        "New Window"                    => "_blank"
    );
    
    // Define Arrays for Tooltips
    $this->TS_VCSC_Tooltip_Style = array(
        "Black"                         => "",
        "Gray"                          => "ts-simptip-style-gray",
        "Green"                         => "ts-simptip-style-green",
        "Blue"                          => "ts-simptip-style-blue",
        "Red"                           => "ts-simptip-style-red",
        "Orange"                        => "ts-simptip-style-orange",
        "Yellow"                        => "ts-simptip-style-yellow",
        "Purple"                        => "ts-simptip-style-purple",
        "Pink"                          => "ts-simptip-style-pink",
        "White"                         => "ts-simptip-style-white"
    );
    $this->TS_VCSC_Tooltip_Position = array(
        "Top"                           => "ts-simptip-position-top",
        "Right"                         => "ts-simptip-position-right",
        "Bottom"                        => "ts-simptip-position-bottom",
        "Left"                          => "ts-simptip-position-left"
    );
    
    // Define Array for MeetThe Team Styles
    $this->TS_VCSC_MeetTeam_Styles = array(
        "Style 1"                       => "style1",
        "Style 2"                       => "style2",
        "Style 3"                       => "style3",
    );
    
    // Define Array for Visual Composer CSS Animations
    $this->TS_VCSC_CSS_Animations = array(
        "None"                          => "",
        "Top to Bottom"                 => "top-to-bottom",
        "Bottom to Top"                 => "bottom-to-top",
        "Left to Right"                 => "left-to-right",
        "Right to Left"                 => "right-to-left",
        "Appear from Center"            => "appear",
    );
    $this->TS_VCSC_CSS_Animations_Values = array(
        'fade-in', 'scale-up', 'right-to-left', 'left-to-right', 'bottom-to-top', 'top-to-bottom'
    );
    
    // Define Array for Hover CSS Animations
    $this->TS_VCSC_CSS_Animations_Effects = array(
        "One Time Effect while Hover"   => "ts-hover-css-",
        "Infinite Effect"               => "ts-infinite-css-",
    );
    $this->TS_VCSC_CSS_Animations_Classes = array(
        "None"                          => "",
        "Bounce"                        => "bounce",
        "Bounce In"                     => "bounceIn",
        "Bounce In Down"                => "bounceInDown",
        "Bounce In Left"                => "bounceInLeft",
        "Bounce In Right"               => "bounceInRight",
        "Bounce In Up"                  => "bounceInUp",
        "Bounce Out"                    => "bounceOut",
        "Bounce Out Down"               => "bounceOutDown",
        "Bounce Out Left"               => "bounceOutLeft",
        "Bounce Out Right"              => "bounceOutRight",
        "Bounce Out Up"                 => "bounceOutUp",
        "Fade In"                       => "fadeIn",
        "Fade In Down"                  => "fadeInDown",
        "Fade In Down Big"              => "fadeInDownBig",
        "Fade In Left"                  => "fadeInLeft",
        "Fade In Left Big"              => "fadeInLeftBig",
        "Fade In Right"                 => "fadeInRight",
        "Fade In Right Big"             => "fadeInRightBig",
        "Fade In Up"                    => "fadeInUp",
        "Fade In Up Big"                => "fadeInUpBig",
        "Fade Out"                      => "fadeOut",
        "Fade Out Down"                 => "fadeOutDown",
        "Fade Out Down Big"             => "fadeOutDownBig",
        "Fade Out Left"                 => "fadeOutLeft",
        "Fade Out Left Big"             => "fadeOutLeftBig",
        "Fade Out Right"                => "fadeOutRight",
        "Fade Out Right Big"            => "fadeOutRightBig",
        "Fade Out Up"                   => "fadeOutUp",
        "Fade Out Up Big"               => "fadeOutUpBig",
        "Flash"                         => "flash",
        "Flip In X"                     => "flipInX",
        "Flip In Y"                     => "flipInY",
        "Flip Out X"                    => "flipOutX",
        "Flip Out Y"                    => "flipOutY",
        "Hinge"                         => "hinge",
        "Light Speed In"                => "lightSpeedIn",
        "Light Speed Out"               => "lightSpeedOut",
        "Pulse"                         => "pulse",
        "Pulse Grow"                    => "pulseGrow",
        "Pulse Shrink"                  => "pulseShrink",
        "Roll In"                       => "rollIn",
        "Roll Out"                      => "rollOut",
        "Rotate Full"                   => "rotateFull",
        "Rotate In"                     => "rotateIn",
        "Rotate In Down Left"           => "rotateInDownLeft",
        "Rotate In Down Right"          => "rotateInDownRight",
        "Rotate In Up Left"             => "rotateInUpLeft",
        "Rotate In Up Right"            => "rotateInUpRight",
        "Rotate Out"                    => "rotateOut",
        "Rotate Out Down Left"          => "rotateOutDownLeft",
        "Rotate Out Down Right"         => "rotateOutDownRight",
        "Rotate Out Up Left"            => "rotateOutUpLeft",
        "Rotate Out Up Right"           => "rotateOutUpRight",
        "Rubberband"                    => "rubberBand",
        "Shake"                         => "shake",
        "Slide In Down"                 => "slideInDown",
        "Slide In Left"                 => "slideInLeft",
        "Slide In Right"                => "slideInRight",
        "Slide Out Left"                => "slideOutLeft",
        "Slide Out Right"               => "slideOutRight",
        "Slide Out Up"                  => "slideOutUp",
        "Spin"                          => "spin",
        "Swing"                         => "swing",
        "Tada"                          => "tada",
        "Wobble"                        => "wobble",
        "Wobble Vertical"               => "wobbleVertical",
        "Wobble Horizontal"             => "wobbleHorizontal",
        "Wobble Top"                    => "wobbleTop",
        "Wobble Bottom"                 => "wobbleBottom",
    );
    
    // Define Array for Hover CSS Animations
    $this->TS_VCSC_CSS_Hovers = array(
        "None"                          => "",
        "Bounce"                        => "ts-hover-css-bounce",
        "Bounce In"                     => "ts-hover-css-bounceIn",
        "Bounce In Down"                => "ts-hover-css-bounceInDown",
        "Bounce In Left"                => "ts-hover-css-bounceInLeft",
        "Bounce In Right"               => "ts-hover-css-bounceInRight",
        "Bounce In Up"                  => "ts-hover-css-bounceInUp",
        "Bounce Out"                    => "ts-hover-css-bounceOut",
        "Bounce Out Down"               => "ts-hover-css-bounceOutDown",
        "Bounce Out Left"               => "ts-hover-css-bounceOutLeft",
        "Bounce Out Right"              => "ts-hover-css-bounceOutRight",
        "Bounce Out Up"                 => "ts-hover-css-bounceOutUp",
        "Fade In"                       => "ts-hover-css-fadeIn",
        "Fade In Down"                  => "ts-hover-css-fadeInDown",
        "Fade In Down Big"              => "ts-hover-css-fadeInDownBig",
        "Fade In Left"                  => "ts-hover-css-fadeInLeft",
        "Fade In Left Big"              => "ts-hover-css-fadeInLeftBig",
        "Fade In Right"                 => "ts-hover-css-fadeInRight",
        "Fade In Right Big"             => "ts-hover-css-fadeInRightBig",
        "Fade In Up"                    => "ts-hover-css-fadeInUp",
        "Fade In Up Big"                => "ts-hover-css-fadeInUpBig",
        "Fade Out"                      => "ts-hover-css-fadeOut",
        "Fade Out Down"                 => "ts-hover-css-fadeOutDown",
        "Fade Out Down Big"             => "ts-hover-css-fadeOutDownBig",
        "Fade Out Left"                 => "ts-hover-css-fadeOutLeft",
        "Fade Out Left Big"             => "ts-hover-css-fadeOutLeftBig",
        "Fade Out Right"                => "ts-hover-css-fadeOutRight",
        "Fade Out Right Big"            => "ts-hover-css-fadeOutRightBig",
        "Fade Out Up"                   => "ts-hover-css-fadeOutUp",
        "Fade Out Up Big"               => "ts-hover-css-fadeOutUpBig",
        "Flash"                         => "ts-hover-css-flash",
        "Flip In X"                     => "ts-hover-css-flipInX",
        "Flip In Y"                     => "ts-hover-css-flipInY",
        "Flip Out X"                    => "ts-hover-css-flipOutX",
        "Flip Out Y"                    => "ts-hover-css-flipOutY",
        "Hinge"                         => "ts-hover-css-hinge",
        "Light Speed In"                => "ts-hover-css-lightSpeedIn",
        "Light Speed Out"               => "ts-hover-css-lightSpeedOut",
        "Pulse"                         => "ts-hover-css-pulse",
        "Pulse Grow"                    => "ts-hover-css-pulseGrow",
        "Pulse Shrink"                  => "ts-hover-css-pulseShrink",
        "Roll In"                       => "ts-hover-css-rollIn",
        "Roll Out"                      => "ts-hover-css-rollOut",
        "Rotate Full"                   => "ts-hover-css-rotateFull",
        "Rotate In"                     => "ts-hover-css-rotateIn",
        "Rotate In Down Left"           => "ts-hover-css-rotateInDownLeft",
        "Rotate In Down Right"          => "ts-hover-css-rotateInDownRight",
        "Rotate In Up Left"             => "ts-hover-css-rotateInUpLeft",
        "Rotate In Up Right"            => "ts-hover-css-rotateInUpRight",
        "Rotate Out"                    => "ts-hover-css-rotateOut",
        "Rotate Out Down Left"          => "ts-hover-css-rotateOutDownLeft",
        "Rotate Out Down Right"         => "ts-hover-css-rotateOutDownRight",
        "Rotate Out Up Left"            => "ts-hover-css-rotateOutUpLeft",
        "Rotate Out Up Right"           => "ts-hover-css-rotateOutUpRight",
        "Rubberband"                    => "ts-hover-css-rubberBand",
        "Shake"                         => "ts-hover-css-shake",
        "Slide In Down"                 => "ts-hover-css-slideInDown",
        "Slide In Left"                 => "ts-hover-css-slideInLeft",
        "Slide In Right"                => "ts-hover-css-slideInRight",
        "Slide Out Left"                => "ts-hover-css-slideOutLeft",
        "Slide Out Right"               => "ts-hover-css-slideOutRight",
        "Slide Out Up"                  => "ts-hover-css-slideOutUp",
        "Spin"                          => "ts-hover-css-spin",
        "Swing"                         => "ts-hover-css-swing",
        "Tada"                          => "ts-hover-css-tada",
        "Wobble"                        => "ts-hover-css-wobble",
        "Wobble Vertical"               => "ts-hover-css-wobbleVertical",
        "Wobble Horizontal"             => "ts-hover-css-wobbleHorizontal",
        "Wobble Top"                    => "ts-hover-css-wobbleTop",
        "Wobble Bottom"                 => "ts-hover-css-wobbleBottom",
    );
    
    $this->TS_VCSC_Infinite_Effects = array(
        "None"                          => "",
        "Bounce"                        => "ts-infinite-css-bounce",
        "Bounce In"                     => "ts-infinite-css-bounceIn",
        "Bounce In Down"                => "ts-infinite-css-bounceInDown",
        "Bounce In Left"                => "ts-infinite-css-bounceInLeft",
        "Bounce In Right"               => "ts-infinite-css-bounceInRight",
        "Bounce In Up"                  => "ts-infinite-css-bounceInUp",
        "Bounce Out"                    => "ts-infinite-css-bounceOut",
        "Bounce Out Down"               => "ts-infinite-css-bounceOutDown",
        "Bounce Out Left"               => "ts-infinite-css-bounceOutLeft",
        "Bounce Out Right"              => "ts-infinite-css-bounceOutRight",
        "Bounce Out Up"                 => "ts-infinite-css-bounceOutUp",
        "Fade In"                       => "ts-infinite-css-fadeIn",
        "Fade In Down"                  => "ts-infinite-css-fadeInDown",
        "Fade In Down Big"              => "ts-infinite-css-fadeInDownBig",
        "Fade In Left"                  => "ts-infinite-css-fadeInLeft",
        "Fade In Left Big"              => "ts-infinite-css-fadeInLeftBig",
        "Fade In Right"                 => "ts-infinite-css-fadeInRight",
        "Fade In Right Big"             => "ts-infinite-css-fadeInRightBig",
        "Fade In Up"                    => "ts-infinite-css-fadeInUp",
        "Fade In Up Big"                => "ts-infinite-css-fadeInUpBig",
        "Fade Out"                      => "ts-infinite-css-fadeOut",
        "Fade Out Down"                 => "ts-infinite-css-fadeOutDown",
        "Fade Out Down Big"             => "ts-infinite-css-fadeOutDownBig",
        "Fade Out Left"                 => "ts-infinite-css-fadeOutLeft",
        "Fade Out Left Big"             => "ts-infinite-css-fadeOutLeftBig",
        "Fade Out Right"                => "ts-infinite-css-fadeOutRight",
        "Fade Out Right Big"            => "ts-infinite-css-fadeOutRightBig",
        "Fade Out Up"                   => "ts-infinite-css-fadeOutUp",
        "Fade Out Up Big"               => "ts-infinite-css-fadeOutUpBig",
        "Flash"                         => "ts-infinite-css-flash",
        "Flip In X"                     => "ts-infinite-css-flipInX",
        "Flip In Y"                     => "ts-infinite-css-flipInY",
        "Flip Out X"                    => "ts-infinite-css-flipOutX",
        "Flip Out Y"                    => "ts-infinite-css-flipOutY",
        "Hinge"                         => "ts-infinite-css-hinge",
        "Light Speed In"                => "ts-infinite-css-lightSpeedIn",
        "Light Speed Out"               => "ts-infinite-css-lightSpeedOut",
        "Pulse"                         => "ts-infinite-css-pulse",
        "Pulse Grow"                    => "ts-infinite-css-pulseGrow",
        "Pulse Shrink"                  => "ts-infinite-css-pulseShrink",
        "Roll In"                       => "ts-infinite-css-rollIn",
        "Roll Out"                      => "ts-infinite-css-rollOut",
        "Rotate Full"                   => "ts-infinite-css-rotateFull",
        "Rotate In"                     => "ts-infinite-css-rotateIn",
        "Rotate In Down Left"           => "ts-infinite-css-rotateInDownLeft",
        "Rotate In Down Right"          => "ts-infinite-css-rotateInDownRight",
        "Rotate In Up Left"             => "ts-infinite-css-rotateInUpLeft",
        "Rotate In Up Right"            => "ts-infinite-css-rotateInUpRight",
        "Rotate Out"                    => "ts-infinite-css-rotateOut",
        "Rotate Out Down Left"          => "ts-infinite-css-rotateOutDownLeft",
        "Rotate Out Down Right"         => "ts-infinite-css-rotateOutDownRight",
        "Rotate Out Up Left"            => "ts-infinite-css-rotateOutUpLeft",
        "Rotate Out Up Right"           => "ts-infinite-css-rotateOutUpRight",
        "Rubberband"                    => "ts-infinite-css-rubberBand",
        "Shake"                         => "ts-infinite-css-shake",
        "Slide In Down"                 => "ts-infinite-css-slideInDown",
        "Slide In Left"                 => "ts-infinite-css-slideInLeft",
        "Slide In Right"                => "ts-infinite-css-slideInRight",
        "Slide Out Left"                => "ts-infinite-css-slideOutLeft",
        "Slide Out Right"               => "ts-infinite-css-slideOutRight",
        "Slide Out Up"                  => "ts-infinite-css-slideOutUp",
        "Spin"                          => "ts-infinite-css-spin",
        "Swing"                         => "ts-infinite-css-swing",
        "Tada"                          => "ts-infinite-css-tada",
        "Wobble"                        => "ts-infinite-css-wobble",
        "Wobble Vertical"               => "ts-infinite-css-wobbleVertical",
        "Wobble Horizontal"             => "ts-infinite-css-wobbleHorizontal",
        "Wobble Top"                    => "ts-infinite-css-wobbleTop",
        "Wobble Bottom"                 => "ts-infinite-css-wobbleBottom",
    );
    
    $this->TS_VCSC_IconBox_Effect = array(
        "None"                          => "",
        "Tilt Up"                       => "ts-css-effect1",
        "Tilt Left"                     => "ts-css-effect2",
        "Tilt Right"                    => "ts-css-effect3",
        "Tilt Left (Up)"                => "ts-css-effect4",
        "Tilt Right (Down)"             => "ts-css-effect5",
        "Grow Out"                      => "ts-css-effect6",
    );
    
    $this->TS_VCSC_IconTitle_Effect = array(
        "None"                          => "",
        "Tilt Up"                       => "ts-css-effect1",
        "Tilt Left"                     => "ts-css-effect2",
        "Tilt Right"                    => "ts-css-effect3",
        "Tilt Left (Up)"                => "ts-css-effect4",
        "Tilt Right (Down)"             => "ts-css-effect5",
        "Grow Out"                      => "ts-css-effect6",
    );
    
    // Define Array for CSS Shadow Types
    $this->TS_VCSC_Shadow_Type = array(
        "None"                          => "",
        "Lifted"                        => "lifted",
        "Raised"                        => "raised",
        "Perspective - Right"           => "perspective-right",
        "Perspective - Left"            => "perspective-left",
        "Curved - Horizontal"           => "curved",
        "Curved - Horizontal (Top)"     => "curved-top",
        "Curved - Horizontal (Bottom)"  => "curved-bottom",
        "Curved - Vertical"             => "curved-vertical",
        "Curved - Vertical (Left)"      => "curved-vertical-left",
        "Curved - Vertical (Right)"     => "curved-vertical-right",
    );
    
    // Define Array for Background Styles
    $this->TS_VCSC_Background_Type = array(
        "Solid Color"                   => "color",
        "Background Pattern"            => "pattern",
    
    );
    $this->TS_VCSC_Background_Type_Values = array(
        'color', 'pattern'
    );
    
    // Define Array for Background Repeat
    $this->TS_VCSC_Repeat_Type = array(
        "Repeat"                        => "repeat",
        "Repeat-X"                      => "repeat-x",
        "Repeat-Y"                      => "repeat-y",
    
    );
    
    // Define Array for Backgrounds
    $this->TS_VCSC_Background_List = array(
        //''                            => 'images/pattern/transparent.png',
        'P00'                           => 'images/pattern/00.jpg',
        'P01'                           => 'images/pattern/01.jpg',
        'P02'                           => 'images/pattern/02.jpg',
        'P03'                           => 'images/pattern/03.jpg',
        'P04'                           => 'images/pattern/04.jpg',
        'P05'                           => 'images/pattern/05.jpg',
        'P06'                           => 'images/pattern/06.jpg',
        'P07'                           => 'images/pattern/07.jpg',
        'P08'                           => 'images/pattern/08.jpg',
        'P09'                           => 'images/pattern/09.jpg',
        'P10'                           => 'images/pattern/10.jpg',
        'P11'                           => 'images/pattern/11.jpg',
        'P12'                           => 'images/pattern/12.jpg',
        'P13'                           => 'images/pattern/13.jpg',
        'P14'                           => 'images/pattern/14.jpg',
        'P15'                           => 'images/pattern/15.jpg',
        'P16'                           => 'images/pattern/16.jpg',
        'P17'                           => 'images/pattern/17.jpg',
        'P18'                           => 'images/pattern/18.jpg',
        'P19'                           => 'images/pattern/19.jpg',
        'P20'                           => 'images/pattern/20.jpg',
        'P21'                           => 'images/pattern/21.jpg',
        'P22'                           => 'images/pattern/22.jpg',
        'P23'                           => 'images/pattern/23.jpg',
        'P24'                           => 'images/pattern/24.jpg',
        'P25'                           => 'images/pattern/25.jpg',
        'P26'                           => 'images/pattern/26.jpg',
        'P27'                           => 'images/pattern/27.jpg',
        'P28'                           => 'images/pattern/28.jpg',
        'P29'                           => 'images/pattern/29.jpg',
        'P30'                           => 'images/pattern/30.jpg',
        'P31'                           => 'images/pattern/31.jpg',
        'P32'                           => 'images/pattern/32.jpg',
        'P33'                           => 'images/pattern/33.jpg',
        'P34'                           => 'images/pattern/34.jpg',
        'P35'                           => 'images/pattern/35.jpg',
        'P36'                           => 'images/pattern/36.jpg',
        'P37'                           => 'images/pattern/37.jpg',
        'P38'                           => 'images/pattern/38.jpg',
        'P39'                           => 'images/pattern/39.jpg',
        'P40'                           => 'images/pattern/40.jpg',
        'P41'                           => 'images/pattern/41.jpg',
        'P42'                           => 'images/pattern/42.jpg',
        'P43'                           => 'images/pattern/43.jpg',
        'P44'                           => 'images/pattern/44.jpg',
        'P45'                           => 'images/pattern/45.jpg',
        'P46'                           => 'images/pattern/46.jpg',
        'P47'                           => 'images/pattern/47.jpg',
        'P48'                           => 'images/pattern/48.jpg',
        'P49'                           => 'images/pattern/49.jpg',
        'P50'                           => 'images/pattern/50.jpg',
        'P51'                           => 'images/pattern/51.jpg',
        'P52'                           => 'images/pattern/52.jpg',
        'P53'                           => 'images/pattern/53.jpg',
        'P54'                           => 'images/pattern/54.jpg',
        'P55'                           => 'images/pattern/55.jpg',
        'P56'                           => 'images/pattern/56.jpg',
        'P57'                           => 'images/pattern/57.jpg',
        'P58'                           => 'images/pattern/58.jpg',
        'P59'                           => 'images/pattern/59.jpg',
        'P60'                           => 'images/pattern/60.jpg',
        'P61'                           => 'images/pattern/61.jpg',
        'P62'                           => 'images/pattern/62.jpg',
        'P63'                           => 'images/pattern/63.jpg',
        'P64'                           => 'images/pattern/64.jpg',
        'P65'                           => 'images/pattern/65.jpg',
        'P66'                           => 'images/pattern/66.jpg',
        'P67'                           => 'images/pattern/67.jpg',
        'P68'                           => 'images/pattern/68.jpg',
        'P69'                           => 'images/pattern/69.jpg',
        'P70'                           => 'images/pattern/70.jpg',
        'P71'                           => 'images/pattern/71.jpg',
        'P72'                           => 'images/pattern/72.jpg',
        'P73'                           => 'images/pattern/73.jpg',
        'P74'                           => 'images/pattern/74.jpg',
        'P75'                           => 'images/pattern/75.jpg',
        'P76'                           => 'images/pattern/76.jpg',
        'P77'                           => 'images/pattern/77.jpg',
        'P78'                           => 'images/pattern/78.jpg',
        'P79'                           => 'images/pattern/79.jpg',
        'P80'                           => 'images/pattern/80.jpg',
        'P81'                           => 'images/pattern/81.jpg',
        'P82'                           => 'images/pattern/82.jpg',
        'P83'                           => 'images/pattern/83.jpg',
        'P84'                           => 'images/pattern/84.jpg',
        'P85'                           => 'images/pattern/85.jpg',
        'P86'                           => 'images/pattern/86.jpg',
        'P87'                           => 'images/pattern/87.jpg',
        'P88'                           => 'images/pattern/88.jpg',
        'P89'                           => 'images/pattern/89.jpg',
        'P90'                           => 'images/pattern/90.jpg',
        'P91'                           => 'images/pattern/91.jpg',
        'P92'                           => 'images/pattern/92.jpg',
        'P93'                           => 'images/pattern/93.jpg',
        'P94'                           => 'images/pattern/94.jpg',
        'P95'                           => 'images/pattern/95.jpg',
        'P96'                           => 'images/pattern/96.jpg',
        'P97'                           => 'images/pattern/97.jpg',
        'P98'                           => 'images/pattern/98.jpg',
        'P99'                           => 'images/pattern/99.jpg',
    );
?>